<?php
    //$children = $this->viewModel()->getCurrent()->getChildren()[0];
?>
<div class="well sidebar-nav">
    <ul class="nav nav-list" id="left-menu">
        <li class="nav-header">Menu</li>
            <li class="active"><a href="/backend/about">About</a></li>
            <li><a href="/backend/pages">Pages</a></li>
            <li><a href="/backend/articles">Articles</a></li>
            <li><a href="/backend/menus">Menus</a></li>
            <li><a href="/backend/media">Media</a></li>
            <li><a href="/backend/users">Users</a></li>
            <li><a href="/backend/settings">Settings</a></li>
            <li><a href="/backend/code-editor">Code Editor</a></li>
            <li><a href="/backend/extra">Extra</a></li>
    </ul>
</div>