<?php
    //$children = $this->viewModel()->getCurrent()->getChildren()[0];
?>
<div class="well sidebar-nav">
    <ul class="nav nav-list" id="left-menu">
        <li class="nav-header">Sidebar</li>
            <li class="active"><a href="/backend/about">About</a></li>
            <li><a href="/backend/pages">Pages</a></li>
            <li><a href="/backend/articles">Articles</a></li>
        <li class="nav-header">Sidebar</li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
    </ul>
</div>