<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Backend\Module'                        => __DIR__ . '/Module.php',
    'Backend\Controller\IndexController' => __DIR__ . '/src/Backend/Controller/IndexController.php',
    'BackendTest\Framework\TestCase'        => __DIR__ . '/tests/Backend/Framework/TestCase.php',
    'BackendTest\SampleTest'                => __DIR__ . '/tests/Backend/SampleTest.php',
);
