<div>
    <div class="row-fluid">
        <div class="span10">
            <div class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#tab1" data-toggle="tab">View All Articles</a>
                    </li>
                    <li>
                        <a href="#tab2" data-toggle="tab">Add Page</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab1">
                        <p>I'm in Section 1.</p>
                    </div>
                    <div class="tab-pane" id="tab2">

                        <?php
                        $form = $this->form;
                        $form->prepare();

                        $form->setAttribute('action', $this->url('backend/pages'));
                        $form->setAttribute('method', 'post');
                        $formLabel = $this->plugin('formLabel');

                        echo $this->form()->openTag($form);

                            $name = $form->get('name');
                            echo "<label>Article Name</label>";
                            echo $this->formInput($name);
                            echo $this->formElementErrors($name);
                            echo $formLabel->closeTag();

                            $content = $form->get('content');
                            echo "<label>Article Content</label>";
                            echo $this->formTextarea($content);
                            echo $this->formElementErrors($content);
                            echo $formLabel->closeTag();

                            echo '<br>';
                            $submit = $form->get('submit');
                            echo $this->formSubmit($submit);

                        echo $this->form()->closeTag();
                        ?>

                        * select layout
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>