<div>
    <div class="row-fluid">
        <div class="span12">
            <div class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#tab1" data-toggle="tab">View All Pages</a>
                    </li>
                    <li>
                        <a href="#tab2" data-toggle="tab">Add Page</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab1">
                        <p>I'm in Section 1.</p>
                    </div>
                    <div class="tab-pane" id="tab2">

                    <?php
                    $form = $this->form;
                    $form->prepare();

                    $form->setAttribute('action', $this->url('backend/pages'));
                    $form->setAttribute('method', 'post');
                    $formLabel = $this->plugin('formLabel');

                    echo $this->form()->openTag($form);

                    $name = $form->get('title');
                    echo $formLabel->openTag() . $name->getOption('label');
                    echo $this->formInput($name);
                    echo $this->formElementErrors($name);
                    echo $formLabel->closeTag();

                    $message = $form->get('content');
                    echo $formLabel->openTag() . $message->getOption('label');
                    echo $this->formTextarea($message);
                    echo $this->formElementErrors($message);
                    echo $formLabel->closeTag();

                    echo $this->form()->closeTag();
                    ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>